version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./ml:/app/ml
      - ./data:/app/data
      - ./services:/app/services
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
      target: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
